### ISSUE TITLE
I dont know how to run this system

### ISSUE THREAD

**Issue by ghost** [mihir0699/Video-Chat#8]
i have downloaded the zip folder containing all the project files. On my terminal i run node index.js within the root folder and open localhost:5000 on chrome. The terminal writes server running on port 5000, then the browser just says running. Now i want to able to open the index file in video-chat-main\client\build in such a way that the video chat app will fully function. Can someone please help me with step by step guide to how to run the app on localhost

**Comment by mihir0699** [comment]
Just run "npm start" inside the client folder and you will be good to go

**Comment by ghost** [comment]
Thank you Mihir.
Provided I face any problem I will hit you up

**Comment by ghost** [comment]
Thanks I did that.
Well I am still a beginner to firebase and react js. I am still confused.
Please help me with step by step guide to how to fully run the application
from start.

ie the pre requisites and from downloading the zip folder what is the next
thing to do. And everything else that follows.

**Comment by ghost** [comment]
Its showing an error
